
input_rds: peng-scRNASeq-manually-filtered-sce-tumour-normal-assigned.rds
annotation_column: cell_type
sample_column: sample

tumour_type: Tumour epithelial
normal_type: Normal epithelial

cutoff: 0.1
denoise: TRUE

samples:
  - CRR034499
  - CRR034500

leiden_res: 0.1
